services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: flask run --host=0.0.0.0 --reload

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
